version: '3.8'

services:
  # Shared database
  shared-db:
    build: ./shared-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-school_management}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # School Portal (SSO Gateway)
  school-portal:
    build: ./school-portal
    restart: always
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@shared-db:5432/${DB_NAME:-school_management}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-nextauth-secret}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret}
      - ADMIN_PORTAL_URL=${ADMIN_PORTAL_URL:-http://admin.schoolname.ac.zw}
      - TEACHER_PORTAL_URL=${TEACHER_PORTAL_URL:-http://teachers.schoolname.ac.zw}
      - ACCOUNTS_PORTAL_URL=${ACCOUNTS_PORTAL_URL:-http://accounts.schoolname.ac.zw}
      - STUDENT_PORTAL_URL=${STUDENT_PORTAL_URL:-http://student.schoolname.ac.zw}
      - DEV_ADMIN_PORTAL_URL=http://admin-portal:3001
      - DEV_TEACHER_PORTAL_URL=http://teacher-portal:3002
      - DEV_ACCOUNTS_PORTAL_URL=http://accounts-portal:3003
      - DEV_STUDENT_PORTAL_URL=http://student-portal:3004
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "3000:3000"
    depends_on:
      - shared-db

  # Admin Portal
  admin-portal:
    build: ./admin-portal
    restart: always
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@shared-db:5432/${DB_NAME:-school_management}
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret}
      - SCHOOL_PORTAL_URL=http://school-portal:3000
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "3001:3000"
    depends_on:
      - shared-db
      - school-portal

  # Teacher Portal
  teacher-portal:
    build: ./teacher-portal
    restart: always
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@shared-db:5432/${DB_NAME:-school_management}
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret}
      - SCHOOL_PORTAL_URL=http://school-portal:3000
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "3002:3000"
    depends_on:
      - shared-db
      - school-portal

  # Accounts Portal
  accounts-portal:
    build: ./accounts-portal
    restart: always
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@shared-db:5432/${DB_NAME:-school_management}
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret}
      - SCHOOL_PORTAL_URL=http://school-portal:3000
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "3003:3000"
    depends_on:
      - shared-db
      - school-portal

  # Student Portal
  student-portal:
    build: ./student-portal
    restart: always
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@shared-db:5432/${DB_NAME:-school_management}
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret}
      - SCHOOL_PORTAL_URL=http://school-portal:3000
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "3004:3000"
    depends_on:
      - shared-db
      - school-portal

  # File Server
  file-server:
    build: ./file_server
    restart: always
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@shared-db:5432/${DB_NAME:-school_management}
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret}
    ports:
      - "8000:8000"
    volumes:
      - file_server_media:/app/media
    depends_on:
      - shared-db

  # Nginx Reverse Proxy (for production-like environments)
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - school-portal
      - admin-portal
      - teacher-portal
      - accounts-portal
      - student-portal
      - file-server

volumes:
  postgres_data:
  file_server_media: